### Importing modules

In [19]:
import tensorflow as tf
import numpy as np
import warnings

warnings.filterwarnings('ignore')

### Tensors Intialization

In [20]:
# creating a scaler tensor
tensor_zero_dim = tf.constant(4)
print(tensor_zero_dim)

tf.Tensor(4, shape=(), dtype=int32)


In [21]:
# creating a 1D tensor
tensor_one_d = tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [22]:
# creating a 2D tensor
tensor_two_d = tf.constant([
    [2,0,-3,8,90],
    [2,0,-3,8,90],
    [2,0,-3,8,90],
    [2,0,-3,8,90]
])

print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3  8 90]
 [ 2  0 -3  8 90]
 [ 2  0 -3  8 90]
 [ 2  0 -3  8 90]], shape=(4, 5), dtype=int32)


In [23]:
# creating a 3D tensor
tensor_three_d = tf.constant([
    [
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90]
    ],
    [
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90]
    ],
    [
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90]
    ],
])

print(tensor_three_d)

tf.Tensor(
[[[ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]]

 [[ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]]

 [[ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]]], shape=(3, 4, 5), dtype=int32)


In [24]:
# tensor string
tensor_string = tf.constant("Hello world")
print(tensor_string)

tf.Tensor(b'Hello world', shape=(), dtype=string)


In [25]:
# tensor boolean
tensor_boolean = tf.constant(True)
print(f"{tensor_boolean}")

True


### Tensors Casting

In [26]:
# Converting integer tensor to float
tensor_one_d = tf.constant([2,0,-3,8,90], dtype=tf.int32)
tensor_one_d_casted = tf.cast(tensor_one_d,dtype=tf.float32)
print(tensor_one_d_casted)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [27]:
# Converting numpy array to tensor
numpy_array = np.array([1,2,3,4,5])
converted_tensor = tf.convert_to_tensor(numpy_array)
print(converted_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


### Tensor Functions

In [28]:
# eye
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(f"{eye_tensor}")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [29]:
# fill
fill_tensor = tf.fill((3,4),6)
print(fill_tensor)

tf.Tensor(
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]], shape=(3, 4), dtype=int32)


In [30]:
# ones
tensor_ones = tf.ones((3,4))
print(tensor_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [31]:
tensor_ones_like = tf.ones_like(
    tensor_three_d,
)
print(tensor_ones_like)

tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(3, 4, 5), dtype=int32)


In [32]:
# zeros
tensor_zeros = tf.zeros(
    (3,4)
)
print(tensor_zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [33]:
# knowing the shape
print(tf.shape(tensor_three_d))

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [36]:
# rank of a tensor
print(tf.rank(tf.constant([1,8,23])))

tf.Tensor(1, shape=(), dtype=int32)


In [38]:
# size of a tensor
print(tf.size(tensor_three_d))

tf.Tensor(60, shape=(), dtype=int32)


#### Random functions

In [50]:
# random values from normal distrubution
# generated random values are centered 
# around the mean specified

random_tensor = tf.random.normal(
    [3,2],
    mean=0,
    stddev=1
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.39550617, -0.29961213],
       [-0.29561213, -1.034551  ],
       [-0.11772624, -0.59361756]], dtype=float32)>