### Importing modules

In [3]:
import tensorflow as tf
import numpy as np
import warnings

warnings.filterwarnings('ignore')

c:\Users\sruja\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


### Tensors Intialization

In [4]:
# creating a scaler tensor
tensor_zero_dim = tf.constant(4)
print(tensor_zero_dim)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
# creating a 1D tensor
tensor_one_d = tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [6]:
# creating a 2D tensor
tensor_two_d = tf.constant([
    [2,0,-3,8,90],
    [2,0,-3,8,90],
    [2,0,-3,8,90],
    [2,0,-3,8,90]
])

print(tensor_two_d)

tf.Tensor(
[[ 2  0 -3  8 90]
 [ 2  0 -3  8 90]
 [ 2  0 -3  8 90]
 [ 2  0 -3  8 90]], shape=(4, 5), dtype=int32)


In [7]:
# creating a 3D tensor
tensor_three_d = tf.constant([
    [
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90]
    ],
    [
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90]
    ],
    [
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90],
        [2,0,-3,8,90]
    ],
])

print(tensor_three_d)

tf.Tensor(
[[[ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]]

 [[ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]]

 [[ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]
  [ 2  0 -3  8 90]]], shape=(3, 4, 5), dtype=int32)


In [8]:
# tensor string
tensor_string = tf.constant("Hello world")
print(tensor_string)

tf.Tensor(b'Hello world', shape=(), dtype=string)


In [9]:
# tensor boolean
tensor_boolean = tf.constant(True)
print(f"{tensor_boolean}")

True


### Tensors Casting

In [10]:
# Converting integer tensor to float
tensor_one_d = tf.constant([2,0,-3,8,90], dtype=tf.int32)
tensor_one_d_casted = tf.cast(tensor_one_d,dtype=tf.float32)
print(tensor_one_d_casted)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [11]:
# Converting numpy array to tensor
numpy_array = np.array([1,2,3,4,5])
converted_tensor = tf.convert_to_tensor(numpy_array)
print(converted_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
