In [1]:
import tensorflow as tf

c:\Users\sruja\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# eye
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(f"{eye_tensor}")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [3]:
# fill
fill_tensor = tf.fill((3,4),6)
print(fill_tensor)

tf.Tensor(
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]], shape=(3, 4), dtype=int32)


In [4]:
# ones
tensor_ones = tf.ones((3,4))
print(tensor_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [13]:
tensor_three_d = tf.fill((3,2,5),7)
ensor_ones_like = tf.ones_like(
    tensor_three_d,
)
print(tensor_ones_like)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [14]:
# zeros
tensor_zeros = tf.zeros(
    (3,4)
)
print(tensor_zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [15]:
# knowing the shape
print(tf.shape(tensor_three_d))

tf.Tensor([3 2 5], shape=(3,), dtype=int32)


In [16]:
# rank of a tensor
print(tf.rank(tf.constant([1,8,23])))

tf.Tensor(1, shape=(), dtype=int32)


In [17]:
# size of a tensor
print(tf.size(tensor_three_d))

tf.Tensor(30, shape=(), dtype=int32)


#### Random functions

In [18]:
# random values from normal distrubution
# generated random values are centered 
# around the mean specified

random_tensor = tf.random.normal(
    [3,2],
    mean=0,
    stddev=1
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.49988827, -1.0069436 ],
       [ 0.15821546,  0.15339857],
       [-1.5455202 ,  1.8774884 ]], dtype=float32)>

In [19]:
# random values from uniform distribution
# the numbers are uniform and not distributed

random_tensor = tf.random.uniform(
    [3,2],
    minval = 0,
    maxval = 8,
    dtype = tf.dtypes.int32,
    seed = None,
    name = None
)

random_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 4],
       [7, 3],
       [1, 5]])>