#### Importing Modules

In [2]:
import tensorflow as tf
import warnings

warnings.filterwarnings('ignore')

c:\Users\sruja\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


#### 1D Indexing

In [3]:
tensor_1d = tf.random.uniform(shape=(5,), minval=1, maxval=50, dtype = tf.dtypes.int32, seed=3)
print(tensor_1d[2:5])

tf.Tensor([27 48 28], shape=(3,), dtype=int32)


#### 2D Indexing

In [4]:
tensor_2d = tf.constant(
    [
        [1,2,3],
        [7,8,9],
        [1,2,3],
        [4,5,6],
    ]
)
print(tensor_2d[1:4,0:2])

tf.Tensor(
[[7 8]
 [1 2]
 [4 5]], shape=(3, 2), dtype=int32)


In [5]:
# ... is used to select all the elements
print(tensor_2d[..., 1])

tf.Tensor([2 8 2 5], shape=(4,), dtype=int32)
